title: Piero Macchioni - Journalist
baseURL: /
params:
  layout_style: grid
  palette: red
  header:
    title: Piero Macchioni
    logo_img: images/logo.png
    has_nav: true
  footer:
    content: '&copy; All rights reserved.'
    links:
      - text: 2020
        url: 'https://www.stackbit.com'
        new_window: true
    has_social: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
